---
- name: Download postfix_exporter
  get_url:
    url: "https://github.com/kumina/postfix_exporter/releases/download/{{ postfix_exporter_version }}/postfix_exporter-{{ postfix_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/postfix_exporter.tar.gz
    mode: '0644'

- name: Extract postfix_exporter
  unarchive:
    src: /tmp/postfix_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy postfix_exporter binary
  copy:
    src: "/tmp/postfix_exporter-{{ postfix_exporter_version }}.linux-amd64/postfix_exporter"
    dest: /usr/local/bin/postfix_exporter
    mode: '0755'
    remote_src: yes

- name: Add postfix_exporter to postfix group
  user:
    name: postfix_exporter
    groups: postfix
    append: yes
    system: yes
    create_home: no
    shell: /bin/false
  ignore_errors: yes

- name: Create postfix_exporter systemd service
  template:
    src: postfix_exporter.service.j2
    dest: /etc/systemd/system/postfix_exporter.service
    mode: '0644'
  notify: restart postfix_exporter

- name: Enable and start postfix_exporter
  systemd:
    name: postfix_exporter
    enabled: yes
    state: started
    daemon_reload: yes
