---
- name: Install dependencies for building postfix_exporter
  apt:
    name:
      - golang-go
      - libsystemd-dev
      - pkg-config
    state: present
    update_cache: yes

- name: Clone postfix_exporter repository
  git:
    repo: 'https://github.com/kumina/postfix_exporter.git'
    dest: /tmp/postfix_exporter_src
    version: master
    force: yes

- name: Build postfix_exporter
  shell: |
    cd /tmp/postfix_exporter_src
    rm -f go.mod go.sum postfix_exporter
    go mod init github.com/kumina/postfix_exporter
    go mod tidy
    go build -o postfix_exporter

- name: Copy postfix_exporter binary
  copy:
    src: /tmp/postfix_exporter_src/postfix_exporter
    dest: /usr/local/bin/postfix_exporter
    mode: '0755'
    remote_src: yes

- name: Add postfix_exporter to postfix group
  user:
    name: postfix_exporter
    groups: postfix
    append: yes
    system: yes
    create_home: no
    shell: /bin/false
  ignore_errors: yes

- name: Create postfix_exporter systemd service
  template:
    src: postfix_exporter.service.j2
    dest: /etc/systemd/system/postfix_exporter.service
    mode: '0644'
  notify: restart postfix_exporter

- name: Enable and start postfix_exporter
  systemd:
    name: postfix_exporter
    enabled: yes
    state: started
    daemon_reload: yes
