---
- name: Download chrony_exporter
  get_url:
    url: "https://github.com/SuperQ/chrony_exporter/releases/download/v{{ chrony_exporter_version }}/chrony_exporter-{{ chrony_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/chrony_exporter.tar.gz
    mode: '0644'

- name: Extract chrony_exporter
  unarchive:
    src: /tmp/chrony_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy chrony_exporter binary
  copy:
    src: "/tmp/chrony_exporter-{{ chrony_exporter_version }}.linux-amd64/chrony_exporter"
    dest: /usr/local/bin/chrony_exporter
    mode: '0755'
    remote_src: yes

- name: Create chrony_exporter systemd service
  template:
    src: chrony_exporter.service.j2
    dest: /etc/systemd/system/chrony_exporter.service
    mode: '0644'
  notify: restart chrony_exporter

- name: Enable and start chrony_exporter
  systemd:
    name: chrony_exporter
    enabled: yes
    state: started
    daemon_reload: yes
